/* Generated by tools/build-index.py. Do not edit by hand.
   Regenerate after adding or renaming a page:
       python3 tools/build-index.py
   11 page(s) indexed. */
window.LEARN_INDEX = [
  {
    "title": "Lesson 01 · The Product Notation",
    "path": "algebra/lessons/0001-the-product-notation.html",
    "subject": "Algebra",
    "type": "lesson",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §1",
    "order": "1.01",
    "status": "current",
    "kicker": "Lesson 01 · Lang, Chapter I, §1, pp. 3–7",
    "summary": "You already know what a monoid is. This is about the machinery Lang builds on top of it, which the next 900 pages assume.",
    "tags": [
      "monoid",
      "submonoid",
      "law of composition",
      "product notation",
      "almost all",
      "empty product",
      "induction",
      "powers"
    ]
  },
  {
    "title": "Reference · Product Notation",
    "path": "algebra/reference/product-notation.html",
    "subject": "Algebra",
    "type": "reference",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §1",
    "order": "1.01",
    "status": "current",
    "kicker": "Reference card · Lang, Chapter I, §1",
    "summary": "One page. Print it. Every entry checked against Lang, pp. 3–7.",
    "tags": [
      "product notation",
      "monoid",
      "submonoid",
      "powers",
      "almost all",
      "subset products",
      "empty product"
    ]
  },
  {
    "title": "Reference · Universal Properties",
    "path": "algebra/reference/universal-properties.html",
    "subject": "Algebra",
    "type": "reference",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §11",
    "order": "1.11",
    "status": "ahead-of-sequence",
    "kicker": "Reference card · Lang, Chapter I, §11",
    "summary": "One page. Print it. Everything here is checked against Lang, pp. 57–59.",
    "tags": [
      "universal object",
      "universally attracting",
      "universally repelling",
      "terminal",
      "initial",
      "product",
      "coproduct",
      "category",
      "unique isomorphism"
    ]
  },
  {
    "title": "Anki deck · I §1",
    "path": "algebra/anki/0001-lang-I-1.tsv",
    "subject": "Algebra",
    "type": "deck",
    "source": "",
    "section": "I §1",
    "order": "9998",
    "status": "current",
    "kicker": "Algebra::Lang::I §1",
    "summary": "18 cards to import into Anki, covering definition, example, hypothesis, meta, notation, proof, theorem.",
    "tags": [
      "lang ch1 s1",
      "level foundation",
      "type definition",
      "type example",
      "type hypothesis",
      "type meta",
      "type notation",
      "type proof",
      "type theorem"
    ]
  },
  {
    "title": "Excel · Course Roadmap",
    "path": "excel/reference/0000-course-roadmap.html",
    "subject": "Excel",
    "type": "reference",
    "source": "Microsoft, Excel help and learning",
    "section": "Tier 0 · Start here",
    "order": "0.00",
    "status": "current",
    "kicker": "Start here · Excel",
    "summary": "Twenty lessons in four tiers, beginner to expert. Tier 1 is written. Open this page first, then work down.",
    "tags": [
      "roadmap",
      "curriculum",
      "start here",
      "beginner to expert",
      "tiers",
      "syllabus"
    ]
  },
  {
    "title": "Lesson 01 · Formulas, Not Numbers",
    "path": "excel/lessons/0001-formulas-not-numbers.html",
    "subject": "Excel",
    "type": "lesson",
    "source": "Microsoft, Excel help and learning",
    "section": "Tier 1 · Foundations",
    "order": "1.01",
    "status": "current",
    "kicker": "Lesson 01 · Tier 1, Foundations",
    "summary": "The one habit that separates a spreadsheet from a calculator. Type the address of a number, never the number itself.",
    "tags": [
      "formula",
      "cell reference",
      "formula bar",
      "recalculation",
      "operator precedence",
      "beginner"
    ]
  },
  {
    "title": "Lesson 02 · The Dollar Sign",
    "path": "excel/lessons/0002-the-dollar-sign.html",
    "subject": "Excel",
    "type": "lesson",
    "source": "Microsoft, Excel help and learning",
    "section": "Tier 1 · Foundations",
    "order": "1.02",
    "status": "current",
    "kicker": "Lesson 02 · Tier 1, Foundations",
    "summary": "Write a formula once and fill it down a thousand rows. One character decides whether that works or quietly produces nonsense.",
    "tags": [
      "absolute reference",
      "relative reference",
      "mixed reference",
      "fill down",
      "F4",
      "beginner"
    ]
  },
  {
    "title": "Reference · Cell References",
    "path": "excel/reference/cell-references.html",
    "subject": "Excel",
    "type": "reference",
    "source": "Microsoft, Excel help and learning",
    "section": "Tier 1 · Foundations",
    "order": "1.02",
    "status": "current",
    "kicker": "Reference card · Tier 1",
    "summary": "One page. Print it. Everything here is used in lesson 2 onward.",
    "tags": [
      "absolute reference",
      "relative reference",
      "mixed reference",
      "F4",
      "structured reference",
      "fill"
    ]
  },
  {
    "title": "Lesson 03 · Tables",
    "path": "excel/lessons/0003-tables.html",
    "subject": "Excel",
    "type": "lesson",
    "source": "Microsoft, Overview of Excel tables",
    "section": "Tier 1 · Foundations",
    "order": "1.03",
    "status": "current",
    "kicker": "Lesson 03 · Tier 1, Foundations",
    "summary": "One keystroke turns a block of cells into an object that knows how big it is. After this, adding 500 rows stops breaking everything.",
    "tags": [
      "Table",
      "structured reference",
      "calculated column",
      "total row",
      "Ctrl+T",
      "beginner"
    ]
  },
  {
    "title": "Lesson 04 · Answering Questions",
    "path": "excel/lessons/0004-answering-questions.html",
    "subject": "Excel",
    "type": "lesson",
    "source": "Microsoft, Excel functions by category",
    "section": "Tier 1 · Foundations",
    "order": "1.04",
    "status": "current",
    "kicker": "Lesson 04 · Tier 1, Foundations",
    "summary": "Adding up everything is easy. Adding up only the rows that match a condition is the first thing that feels like analysis.",
    "tags": [
      "SUMIFS",
      "COUNTIFS",
      "AVERAGEIFS",
      "criteria",
      "summary block",
      "beginner"
    ]
  },
  {
    "title": "Reference · Aggregation",
    "path": "excel/reference/aggregation.html",
    "subject": "Excel",
    "type": "reference",
    "source": "Microsoft, Excel functions by category",
    "section": "Tier 1 · Foundations",
    "order": "1.04",
    "status": "current",
    "kicker": "Reference card · Tier 1",
    "summary": "One page. Print it. The argument order and the condition forms, which are the two things people look up again and again.",
    "tags": [
      "SUMIFS",
      "COUNTIFS",
      "AVERAGEIFS",
      "criteria",
      "wildcards",
      "aggregation",
      "summary"
    ]
  }
];
