/* Generated by tools/build-index.py. Do not edit by hand.
   Regenerate after adding or renaming a page:
       python3 tools/build-index.py
   3 page(s) indexed. */
window.LEARN_INDEX = [
  {
    "title": "Lesson 01 · The Product Notation",
    "path": "algebra/lessons/0001-the-product-notation.html",
    "subject": "Algebra",
    "type": "lesson",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §1",
    "order": "1.01",
    "status": "current",
    "kicker": "Lesson 01 · Lang, Chapter I, §1, pp. 3–7",
    "summary": "You already know what a monoid is. This is about the machinery Lang builds on top of it, which the next 900 pages assume.",
    "tags": [
      "monoid",
      "submonoid",
      "law of composition",
      "product notation",
      "almost all",
      "empty product",
      "induction",
      "powers"
    ]
  },
  {
    "title": "Reference · Product Notation",
    "path": "algebra/reference/product-notation.html",
    "subject": "Algebra",
    "type": "reference",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §1",
    "order": "1.01",
    "status": "current",
    "kicker": "Reference card · Lang, Chapter I, §1",
    "summary": "One page. Print it. Every entry checked against Lang, pp. 3–7.",
    "tags": [
      "product notation",
      "monoid",
      "submonoid",
      "powers",
      "almost all",
      "subset products",
      "empty product"
    ]
  },
  {
    "title": "Reference · Universal Properties",
    "path": "algebra/reference/universal-properties.html",
    "subject": "Algebra",
    "type": "reference",
    "source": "Lang, Algebra (GTM 211)",
    "section": "I §11",
    "order": "1.11",
    "status": "ahead-of-sequence",
    "kicker": "Reference card · Lang, Chapter I, §11",
    "summary": "One page. Print it. Everything here is checked against Lang, pp. 57–59.",
    "tags": [
      "universal object",
      "universally attracting",
      "universally repelling",
      "terminal",
      "initial",
      "product",
      "coproduct",
      "category",
      "unique isomorphism"
    ]
  }
];
